// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright (c) Status Research & Development GmbH

// Unity build chunk for BoringSSL sources. Keep in sync with prelude.nim.
#include "../boringssl/crypto/asn1/a_bitstr.cc"
#include "../boringssl/crypto/asn1/a_bool.cc"
#include "../boringssl/crypto/asn1/a_d2i_fp.cc"
#include "../boringssl/crypto/asn1/a_dup.cc"
#include "../boringssl/crypto/asn1/a_gentm.cc"
#include "../boringssl/crypto/asn1/a_i2d_fp.cc"
#include "../boringssl/crypto/asn1/a_int.cc"
#include "../boringssl/crypto/asn1/a_mbstr.cc"
#include "../boringssl/crypto/asn1/a_object.cc"
#include "../boringssl/crypto/asn1/a_octet.cc"
#include "../boringssl/crypto/asn1/a_strex.cc"
#include "../boringssl/crypto/asn1/a_strnid.cc"
#include "../boringssl/crypto/asn1/a_time.cc"
#include "../boringssl/crypto/asn1/a_type.cc"
#include "../boringssl/crypto/asn1/a_utctm.cc"
#include "../boringssl/crypto/asn1/asn1_lib.cc"
#include "../boringssl/crypto/asn1/asn1_par.cc"
#include "../boringssl/crypto/asn1/asn_pack.cc"
#include "../boringssl/crypto/asn1/f_int.cc"
#include "../boringssl/crypto/asn1/f_string.cc"
#include "../boringssl/crypto/asn1/posix_time.cc"
#include "../boringssl/crypto/asn1/tasn_dec.cc"
#include "../boringssl/crypto/asn1/tasn_enc.cc"
#include "../boringssl/crypto/asn1/tasn_fre.cc"
#include "../boringssl/crypto/asn1/tasn_new.cc"
#include "../boringssl/crypto/asn1/tasn_typ.cc"
#include "../boringssl/crypto/asn1/tasn_utl.cc"
